import type { Metadata } from "next";
import Link from "next/link";
import { Box, Download, ExternalLink, PlugZap, ShieldCheck, Terminal } from "lucide-react";
import { AurelGridSection, AurelPublicHeader, AurelPublicMain } from "@/app/components/AurelPublicShell";

export const metadata: Metadata = {
  title: "Aurels Plugins",
  description:
    "Download Aurels plugins and framework integrations for Codex, Hermes, CrewAI, OpenClaw, and agent runtime tool guards.",
  alternates: { canonical: "/plugins" },
};

const plugins = [
  {
    name: "Complete agent bundle",
    file: "aurel-agent-integrations.zip",
    size: "95 KB",
    icon: Box,
    summary: "All packaged agent integrations in one archive for offline review and internal distribution.",
    command: "npm run package:agent-integrations",
    bestFor: "Teams shipping multiple agent runtimes",
  },
  {
    name: "Codex plugin",
    file: "aurel-codex-plugin.zip",
    size: "2.7 KB",
    icon: Terminal,
    summary: "Repo-local Codex plugin that routes protected MCP tools through the Aurels policy gate.",
    command: "npm run package:codex-plugin",
    bestFor: "Codex MCP workflows",
  },
  {
    name: "Hermes plugin",
    file: "aurel-hermes-plugin.zip",
    size: "13 KB",
    icon: PlugZap,
    summary: "Hermes Agent plugin with preflight enforcement, redaction, telemetry, and fail-mode controls.",
    command: "npm run package:hermes-plugin",
    bestFor: "Hermes Agent deployments",
  },
  {
    name: "CrewAI integration",
    file: "aurel-crewai-integration.zip",
    size: "8.8 KB",
    icon: ShieldCheck,
    summary: "Python guard for CrewAI tools before high-consequence agent tasks execute.",
    command: "npm run package:crewai-integration",
    bestFor: "CrewAI crews and automations",
  },
  {
    name: "OpenClaw plugin",
    file: "aurel-openclaw-plugin-0.1.0.tgz",
    size: "21 KB",
    icon: ExternalLink,
    summary: "Packaged OpenClaw plugin with TypeScript types and pre-execution security hooks.",
    command: "npm run package:openclaw-plugin",
    bestFor: "OpenClaw 2026 plugin installs",
  },
];

export default function PluginsPage() {
  return (
    <AurelPublicMain>
      <AurelPublicHeader eyebrow="Downloads / agent plugins" title="Download Aurels plugins">
        Install Aurels directly into the agent runtimes that execute tools. Each package below is generated
        from this repository and ships with the adapter code needed to preflight actions before side effects.
      </AurelPublicHeader>

      <AurelGridSection>
        <div className="mb-8 grid gap-6 lg:grid-cols-[0.7fr_1fr] lg:items-end">
          <div>
            <div className="aurel-kicker mb-3">Plugin shelf</div>
            <h2 className="aurel-title text-3xl md:text-5xl">Pick the runtime, pull the gate.</h2>
          </div>
          <p className="max-w-2xl text-lg leading-8 text-stone-400">
            Downloads are served from a small allowlisted endpoint. If a package is missing, rebuild it locally
            with the command shown on its card.
          </p>
        </div>
        <div className="mb-6 flex flex-col gap-3 border border-stone-800 bg-black/55 p-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="font-mono text-[10px] uppercase tracking-[0.16em] text-stone-700">Artifact integrity</div>
            <p className="mt-1 text-sm text-stone-400">
              Compare downloaded packages against the SHA-256 manifest generated by the packaging pipeline.
            </p>
          </div>
          <Link href="/api/downloads/manifest" className="aurel-button-ghost gap-2 px-4 py-3 text-center">
            <ShieldCheck className="h-4 w-4" />
            Manifest
          </Link>
        </div>

        <div className="grid gap-px border border-stone-800 bg-stone-800 md:grid-cols-2">
          {plugins.map((plugin) => (
            <article key={plugin.file} className="aurel-surface-line bg-black/60 p-6">
              <div className="mb-7 flex items-start justify-between gap-4">
                <div className="flex h-11 w-11 items-center justify-center border border-stone-700 bg-stone-950">
                  <plugin.icon className="h-5 w-5 text-stone-300" />
                </div>
                <span className="border border-stone-800 px-2.5 py-1 font-mono text-[10px] uppercase tracking-[0.14em] text-stone-500">
                  {plugin.size}
                </span>
              </div>
              <h3 className="text-xl font-black uppercase tracking-tight text-stone-100">{plugin.name}</h3>
              <p className="mt-3 min-h-[72px] text-sm leading-7 text-stone-500">{plugin.summary}</p>

              <div className="mt-5 border border-stone-800 bg-black/70 p-3 font-mono text-[11px] leading-6 text-stone-400">
                <div className="text-stone-600"># rebuild artifact</div>
                <div>{plugin.command}</div>
              </div>

              <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <div className="font-mono text-[10px] uppercase tracking-[0.16em] text-stone-700">Best for</div>
                  <div className="mt-1 text-sm text-stone-300">{plugin.bestFor}</div>
                </div>
                <a
                  href={`/api/downloads/${plugin.file}`}
                  className="aurel-button gap-2 px-4 py-3 text-center"
                >
                  <Download className="h-4 w-4" />
                  Download
                </a>
              </div>
            </article>
          ))}
        </div>
      </AurelGridSection>

      <AurelGridSection>
        <div className="grid gap-8 lg:grid-cols-[0.78fr_1fr] lg:items-center">
          <div>
            <div className="aurel-kicker mb-3">Setup path</div>
            <h2 className="aurel-title text-2xl md:text-4xl">Install, point at the API, verify.</h2>
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            {["Set AUREL_API_URL", "Set AUREL_API_KEY", "Run a protected tool"].map((step, index) => (
              <div key={step} className="border border-stone-800 bg-black/55 p-4">
                <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-stone-700">
                  0{index + 1}
                </div>
                <div className="mt-4 text-sm font-bold uppercase tracking-wide text-stone-200">{step}</div>
              </div>
            ))}
          </div>
        </div>
        <div className="mt-8 flex flex-wrap gap-3">
          <Link href="/docs" className="aurel-button-ghost px-4 py-3">
            Read docs
          </Link>
          <Link href="/dashboard/integrations" className="aurel-button-ghost px-4 py-3">
            Dashboard integrations
          </Link>
          <Link href="/benchmark" className="aurel-button-ghost px-4 py-3">
            Benchmark results
          </Link>
        </div>
      </AurelGridSection>
    </AurelPublicMain>
  );
}
