export type Currency = "USD" | "EUR" | "GBP" | "USDC" | "USDT" | string;

/** Payload sent by an agentic system to /api/verify. Payment is the first supported action shape. */
export interface PaymentIntent {
  /** Unique ID generated by the caller for idempotency */
  intent_id: string;
  /** Originating agent identifier */
  agent_id: string;
  /** End-user / workspace owning the agent */
  workspace_id: string;
  amount: number;
  currency: Currency;
  /** Recipient wallet address, IBAN, or identifier */
  recipient: string;
  /** Merchant / platform identifier (optional) */
  merchant_id?: string;
  /** Agent's natural-language reasoning for this action — stored for auditing */
  agent_context?: string;
  /** Declared operational mission used by semantic analysis to detect mission drift. */
  mission_scope?: string;
  /** Optional signed user mandate that constrains this payment intent. */
  mandate?: import("@/lib/mandates").SignedMandate;
  /** Free-form context forwarded by the agent */
  metadata?: Record<string, unknown>;
}

export type RuleDecision = "allow" | "block" | "flag";
export type ApiKeyRole = "admin" | "operator" | "viewer";

export interface RuleResult {
  decision: RuleDecision;
  rule_id: string;
  reason: string;
  risk_score: number; // 0–100
}

export interface VerifyResponse {
  /** Simplified verdict for agent consumption */
  decision: RuleDecision;
  reason: string;
  /** Which rule triggered the final verdict (UUID) */
  triggered_rule?: string;
  risk_score: number;
  /** ISO 8601 timestamp */
  evaluated_at: string;
  intent_id: string;
  /** HMAC-SHA256 proof over the persisted audit decision record. */
  audit_signature?: string;
  audit_signature_version?: string;
}

// ─── Supabase DB row shapes ───────────────────────────────────────────────────

export interface DbWorkspace {
  id: string;
  name: string;
  policy: Record<string, unknown>; // typed as WorkspacePolicy at runtime
  created_at: string;
}

export interface DbApiKey {
  id: string;
  workspace_id: string;
  key_hash: string; // SHA-256 of the raw key
  name: string;
  role: ApiKeyRole;
  is_active: boolean;
  last_used_at: string | null;
  revoked_at: string | null;
  created_at: string;
}

export interface DbRule {
  id: string;
  workspace_id: string;
  rule_type:
    | "amount_threshold"
    | "allowlist"
    | "denylist"
    | "velocity_count"
    | "velocity_amount";
  priority: number; // lower = evaluated first
  config: Record<string, unknown>;
  is_active: boolean;
  created_at: string;
}

export interface DbVerifyLog {
  id: string;
  intent_id: string;
  intent_payload_hash: string | null;
  workspace_id: string;
  agent_id: string;
  recipient: string;
  merchant_id: string | null;
  amount: number;
  currency: string;
  agent_context: string | null;
  decision: RuleDecision;
  triggered_rule: string | null;
  risk_score: number;
  review_status: "not_required" | "pending" | "approved" | "rejected";
  review_note: string | null;
  reviewed_at: string | null;
  audit_signature: string | null;
  audit_signature_version: string | null;
  created_at: string;
}

export interface DbActionAuditLog {
  id: string;
  workspace_id: string;
  action_id: string;
  integration: string;
  agent_id: string | null;
  decision: "allow" | "block" | "require_approval" | "rewrite" | "quarantine";
  reason: string | null;
  risk_score: number;
  rule_ids: string[];
  policy_version: string | null;
  trace_id: string | null;
  payload_hash: string;
  audit_signature: string;
  audit_signature_version: string;
  created_at: string;
}

export interface DbWorkspaceMember {
  id: string;
  workspace_id: string;
  user_id: string;
  role: ApiKeyRole;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
