export type Currency = "USD" | "EUR" | "GBP" | "USDC" | "USDT" | string;

/** Payload sent by an agentic system to /api/verify */
export interface PaymentIntent {
  /** Unique ID generated by the caller for idempotency */
  intent_id: string;
  /** Originating agent identifier */
  agent_id: string;
  /** End-user / workspace owning the agent */
  workspace_id: string;
  amount: number;
  currency: Currency;
  /** Recipient wallet address, IBAN, or identifier */
  recipient: string;
  /** Merchant / platform identifier (optional) */
  merchant_id?: string;
  /** Agent's natural-language reasoning for this payment — stored for auditing */
  agent_context?: string;
  /** Free-form context forwarded by the agent */
  metadata?: Record<string, unknown>;
}

export type RuleDecision = "allow" | "block" | "flag";

export interface RuleResult {
  decision: RuleDecision;
  rule_id: string;
  reason: string;
  risk_score: number; // 0–100
}

export interface VerifyResponse {
  /** Simplified verdict for agent consumption */
  decision: RuleDecision;
  reason: string;
  /** Which rule triggered the final verdict (UUID) */
  triggered_rule?: string;
  risk_score: number;
  /** ISO 8601 timestamp */
  evaluated_at: string;
  intent_id: string;
}

// ─── Supabase DB row shapes ───────────────────────────────────────────────────

export interface DbWorkspace {
  id: string;
  name: string;
  policy: Record<string, unknown>; // typed as WorkspacePolicy at runtime
  created_at: string;
}

export interface DbApiKey {
  id: string;
  workspace_id: string;
  key_hash: string; // SHA-256 of the raw key
  name: string;
  is_active: boolean;
  created_at: string;
}

export interface DbRule {
  id: string;
  workspace_id: string;
  rule_type:
    | "amount_threshold"
    | "allowlist"
    | "denylist"
    | "velocity_count"
    | "velocity_amount";
  priority: number; // lower = evaluated first
  config: Record<string, unknown>;
  is_active: boolean;
  created_at: string;
}

export interface DbVerifyLog {
  id: string;
  intent_id: string;
  workspace_id: string;
  agent_id: string;
  recipient: string;
  merchant_id: string | null;
  amount: number;
  currency: string;
  agent_context: string | null;
  decision: RuleDecision;
  triggered_rule: string | null;
  risk_score: number;
  created_at: string;
}
